-- 시퀀스를 생성해보자
CREATE SEQUENCE SEQ1; --1부터 1씩 자동증가하는 시퀀스객체가 생성
CREATE SEQUENCE SEQ2 START WITH 1 INCREMENT BY 1; --위와 같다
CREATE SEQUENCE SEQ3 START WITH 1 INCREMENT BY 1 NOCACHE;--위와 같으나 CACHE사이즈를 20에서 0으로 변경
CREATE SEQUENCE SEQ4 START WITH 1 INCREMENT BY 1 MAXVALUE 100 NOCACHE;--MAX값을 100까지만
CREATE SEQUENCE SEQ5 START WITH 5 INCREMENT BY 5 NOCACHE;
-- 시퀀스전체정보를 출력
SELECT * FROM SEQ;

--시퀀스값을 발생시켜보자-한번발생한값들은 두번다시 안나온다
SELECT SEQ1.NEXTVAL,SEQ2.NEXTVAL,SEQ3.NEXTVAL,SEQ4.NEXTVAL,SEQ5.NEXTVAL FROM DUAL;

--시퀀스 제거
DROP SEQUENCE SEQ1;
DROP SEQUENCE SEQ2;
DROP SEQUENCE SEQ3;
DROP SEQUENCE SEQ4;
DROP SEQUENCE SEQ5;


-- TABLE 생성
CREATE TABLE TEST1 (
    NUM NUMBER(3) PRIMARY KEY,
    NAME VARCHAR2(20) NOT NULL,
    TODAY DATE);
    
-- 구조 확인
DESC TEST1;

--데이타 추가
INSERT INTO TEST1 VALUES (1,'CANDY',SYSDATE);--컬럼명 생략시 모든 컬럼을 순서대로 값을 넣는다
--PRIMARY KEY 에 같은 값을 넣었을경우 어떤 오류가 나오는지 확인하기
INSERT INTO TEST1 VALUES (1,'MIRA',SYSDATE);--오류 확인하기 ,무결성 제약조건으로 코드번호가 뜬다
--이번에는 이름을빼고 넣은후 오류를 확인해보자
INSERT INTO TEST1 (NUM,TODAY) VALUES (2,SYSDATE);--ORA-01400: NULL을 ("ANGEL"."TEST1"."NAME") 안에 삽입할 수 없습니다

--이번에는 전체 데이타를 넣는데 순서를 바꿔서 넣어보자
INSERT INTO TEST1 (NUM,TODAY,NAME) VALUES (2,'2024-11-20','MIRA');

-- INSERT 를 2개 추가한상태에서 ROLLBACK을 해보자
ROLLBACK;
--다시 위의 INSERT 문 실행해서 넣어보자. 넣은후 COMMIT 하기
COMMIT;
--COMMIT 을 한후 ROLLBACK 해도 취소 안됨
ROLLBACK;

--데이타 확인
SELECT * FROM TEST1;

-- TEST2는 TEST1 과 같은데 제약조건이름을 추가해서 생성해보자
CREATE TABLE TEST2(
    NUM NUMBER(3) CONSTRAINT PK_TEST2_NUM PRIMARY KEY,
    NAME VARCHAR2(20) CONSTRAINT NN_TEST2_NAME NOT NULL,
    TODAY DATE);

-- 오류 발생을 시켜보자
INSERT INTO TEST2 VALUES (1,'이영자',SYSDATE);--추가됨
INSERT INTO TEST2 VALUES (1,'김말자',SYSDATE);--오류발생,무결성 제약 조건(ANGEL.PK_TEST2_NUM)에 위배됩니다

SELECT * FROM TEST2;

--테이블의 구조변경 , ALTER TABLE
--컬럼 추가 : ADD,컬럼 삭제: DROP COLUMN,컬럼 수정:MODIFY, 컬럼명변경:RENAME COLUMN

-- TEST1 에 AGE NUMBER(3) 컬럼 추가하기,일단은 값은 NULL 로 들어감
ALTER TABLE TEST1 ADD AGE NUMBER(3);

--TEST1 에 ADDR VARCHAR2(30) 추가하는데 기본값을 SEOUL 로 주고싶다
ALTER TABLE TEST1 ADD ADDR VARCHAR2(30) DEFAULT 'SEOUL';

--TEST1 에 GAIPDAY DATE 으로 추가하는데 기본값을 현재날짜로
ALTER TABLE TEST1 ADD GAIPDAY DATE DEFAULT SYSDATE;

--TEST1의 TODAY 컬럼 삭제하기
ALTER TABLE TEST1 DROP COLUMN TODAY;

--TEST1의 NAME 의 길이를 20에서 30으로 수정해보자
ALTER TABLE TEST1 MODIFY NAME VARCHAR2(30);

--TEST1 의 ADDR 을 ADDRESS 로 컬럼명을 변경해보자
ALTER TABLE TEST1 RENAME COLUMN ADDR TO ADDRESS;

--TEST1 의 GAIPDAY를 WRITEDAY 로 이름변경
ALTER TABLE TEST1 RENAME COLUMN GAIPDAY TO WRITEDAY;

--TEST1 의 제약조건중 SYS_C008317(임시이름) 을 제거해보자
ALTER TABLE TEST1 DROP CONSTRAINT SYS_C008317;

--TEST1에 제약조건을 추가 : AGE 의 나이범위가 10~30으로 , 제약조건명:CK_TEST1_AGE

ALTER TABLE TEST1 ADD CONSTRAINT CK_TEST1_AGE CHECK (AGE>=10 AND AGE<=30);

--AGE 에 번위를 벗어나게 추가해서 오류 확인 하기 
INSERT INTO TEST1 (NUM,NAME,AGE) VALUES (3,'SON',35); --(ANGEL.CK_TEST1_AGE ) 체크 제약 조건 위배 

--5분 문제 ㅋㅋ ;TEST2 로 하기 

-- 1. TEST2에 BLOOD VARCHAR2(10) 초기값은 A로 추가하기 
ALTER TABLE TEST2 ADD BLOOD VARCHAR2(10) DEFAULT 'B';
-- 2. TEST2에서 TODAY COLUMN 제거 하기 
ALTER TABLE TEST2 DROP COLUMN TODAY;
-- 3. TEST2의 NAME을 SAWON_NAME 으로 컬럼이름 변경하기 
ALTER TABLE TEST2 RENAME COLUMN NAME TO SAWON_NAME;

SELECT * FROM TEST2;
DESC TEST2;


--4.blood 의 제약조건 추가 (A,B,O,AB 만 가능하도록 check )
ALTER TABLE TEST2 ADD CONSTRAINT CK_TEST2_BLOOD CHECK (BLOOD IN('A','B','O','AB'));

-- NN_TEST2_NAME 이라는 제약조건을 젝어 하기
ALTER TABLE TEST2 DROP CONSTRAINT NN_TEST2_NAME;


drop table test1 ;
drop table test2 ; 

-----------------------------------------------------------------------------------------------------
--시퀀스 생성 

create sequence SEQ1 NOCACHE; -- 1부터 1씩 증가하는 CACHE가 없는 시퀀스 생성.


--- 테이블 생성 

CREATE TABLE SAWON(
    NUM NUMBER(3) CONSTRAINT PK_SAWON_NUM PRIMARY KEY,
    NAME VARCHAR2(20),
    BUSEO VARCHAR2(20),
    GENDER VARCHAR2 (10) DEFAULT '남자',
    AGE NUMBER(3),
    HEIGHT NUMBER(5,1),
    WERITEDAY DATE);
    
    
--제약 조건 추가 :부서명은 '홍보부','교육부','관리부' 만 가능하다 
ALTER TABLE SAWON ADD CONSTRAINT CK_SAWON_BUSEO CHECK (BUSEO IN('홍보부','교육부','관리부'));

--제약조건 추가: 성별은 '남자','여자' 만 가능하다
ALTER TABLE SAWON ADD CONSTRAINT CK_SAWON_GENDER CHECK(GENDER IN('남자','여자'));


-- 데이터 추가
INSERT INTO SAWON VALUES (SEQ1.NEXTVAL,'이진구','홍보부','여자',29,167.8,SYSDATE);
INSERT INTO SAWON (NUM,NAME,BUSEO,AGE) VALUES (SEQ1.NEXTVAL, '강호동','관리부',36);
INSERT INTO SAWON (NUM,NAME,BUSEO,HEIGHT) VALUES (SEQ1.NEXTVAL, '이재석','교육부',175.8);
INSERT INTO SAWON (NUM,NAME,BUSEO,GENDER,AGE, WERITEDAY) VALUES (SEQ1.NEXTVAL, '고정민','교육부','여자',27,SYSDATE);
INSERT INTO SAWON VALUES(SEQ1.NEXTVAL,'송해나','홍보부','여자','31',159.9,SYSDATE);
COMMIT;



--UPDATE 수정
UPDATE SAWON SET HEIGHT = 185.1;--만약 WHERE 조건을 안쓰면 전체 데이터가 수정된다 

--다시 취소 
ROLLBACK;

--NUM=3인 경우만 수정 
UPDATE SAWON SET HEIGHT = 185.9 WHERE NUM = 3;

-- 여러 컬럼을 수정하는 경우 
UPDATE SAWON SET BUSEO = '홍보부',AGE = 39, HEIGHT = 162.1 WHERE NAME ='송해나';

--WRITEDAY == NULL 일 경우 '2024-12-12'로 변경을 해보자
UPDATE SAWON SET WERITEDAY = '2024-12-12' WHERE WERITEDAY IS NULL;


--삭제 DELETE 형식 -> DELETE FROM TABLE명 WHERE 조건 (WHERE 조건을 안쓰면 전체 데이터가 삭제)
DELETE FROM SAWON;
-- ROLLBACK
ROLLBACK;

--AGE 가 NULL인 데이터는 모두 삭제
DELETE FROM SAWON WHERE AGE IS NULL;

--GROUP BY  연습

-- 부서별 인원수 와 평균나이를 구하시오 
SELECT BUSEO 부서,COUNT(*) 인원수, ROUND(AVG(AGE),0) FROM SAWON GROUP BY BUSEO;
--성별 인원수와 평균 나이를 구하시오 
SELECT GENDER 성별, COUNT(*) 인원수,ROUND(AVG(AGE),0) FROM SAWON GROUP BY GENDER;
-----------------------------------------------------------------------------------------------------



DESC SAWON;
SELECT * FROM SAWON;

------------------------------------------------------------------------------
--JOIN 용 연습 테이블 생성
CREATE TABLE FOOD(
    FOODNUM NUMBER(3) PRIMARY KEY,
    FOODNAME VARCHAR2 (20),
    FOODPRICE NUMBER(7),
    FOODSIZE VARCHAR2(20));

CREATE TABLE BOOKING(
    BNUM NUMBER(3) CONSTRAINT PK_BOOKING_BNUM PRIMARY KEY,
    BNAME VARCHAR2(20) CONSTRAINT NN_BOOKING_BNAME NOT NULL,
    BHP VARCHAR2(20) CONSTRAINT UQ_BOOKING_BHP UNIQUE,
    FOODNUM NUMBER(3),
    BOOKINGDAY DATE,
    CONSTRAINT FK_FOODNUM FOREIGN KEY(FOODNUM) REFERENCES FOOD(FOODNUM));

---=메뉴 등록
INSERT INTO FOOD VALUES(100,'짜장면',9000,'보통');
INSERT INTO FOOD VALUES(101,'짜장면',11000,'곱빼기');
INSERT INTO FOOD VALUES(200,'탕수육',15000,'보통');
INSERT INTO FOOD VALUES(201,'탕수육',20000,'곱빼기');
INSERT INTO FOOD VALUES(300,'칠리새우',15000,'소');
INSERT INTO FOOD VALUES(301,'칠리새우',30000,'대');
INSERT INTO FOOD VALUES(400,'해물짬뽕',11000,'보통');

COMMIT;
SELECT * FROM FOOD;

--시퀀스 생성
CREATE SEQUENCE SEQ_FOOD START WITH 10 INCREMENT BY 10 NOCACHE;

--예약


INSERT INTO BOOKING VALUES (SEQ_FOOD.NEXTVAL,'이영자','010-2688-8888',200,'2024-12-24');

--오류 발생 시켜보기 (ANGEL.FK_FOODNUM) 위배 -> 메뉴에 없는걸 시킴 ;
INSERT INTO BOOKING VALUES (SEQ_FOOD.NEXTVAL,'김말자','010-2688-7777',401,'2025-1-10');
--오류 고치기
INSERT INTO BOOKING VALUES (SEQ_FOOD.NEXTVAL,'이영자','010-2688-7777',301,'2024-12-24');


INSERT INTO BOOKING VALUES (SEQ_FOOD.NEXTVAL,'효리이','010-1234-8888',400,'2024-12-31');
INSERT INTO BOOKING VALUES (SEQ_FOOD.NEXTVAL,'손예진','010-4312-8888',201,'2025-1-24');
COMMIT;

--INNER JOIN 으로 예약손님의 주문 정보를 확인하자

SELECT 
    BNAME,BHP,FOODNAME,FOODSIZE,FOODPRICE,TO_CHAR(BOOKINGDAY,'YYYY-MM-DD') BOOKINGDAY 
    FROM FOOD F, BOOKING B 
    WHERE F.FOODNUM = B.FOODNUM;

--OUTER JOIN 을 이용해 한번도 주문하지 않은 메뉴들을 알아보자

SELECT 
    F.FOODNUM,BNAME,FOODNAME,FOODPRICE,FOODSIZE
    FROM  FOOD F, BOOKING B
    WHERE F.FOODNUM=B.FOODNUM(+); --이때 아무도 주문하지 않은 음식들은 NULL로 나옴 
    
    --위의 SQL 문을 이용해서 주문자 이름을 빼고 NULL인 경우만 출력하면 아무도 주문하지 않은 메뉴만 골라낼 수 있다.

SELECT 
    F.FOODNUM,BNAME,FOODNAME,FOODPRICE,FOODSIZE
    FROM  FOOD F, BOOKING B
    WHERE F.FOODNUM=B.FOODNUM(+) AND BNAME IS NULL;
    
    --BOOKING (자식테이블)에 추가된 메뉴를 FOOD(부모테이블) 에서 삭제할 수 있을까 ? 
    --자식 테이블 생성시 ON DELETE CASCADE 설정을 안했을경우는 못지움
    DELETE FROM FOOD WHERE FOODNUM = 200; -- CASCADE 삭제를 못함  -> 한번이라도 예약이 되면 참조가 되기 때문에 삭제 X
    --BUT 한번도 참조되지않은 것은 삭제 가능
     DELETE FROM FOOD WHERE FOODNUM = 300; --> 삭제 가능 기모디

--부모 테이블을 삭제해보자
DROP TABLE FOOD; -->당연히 삭제 안됨, 자식테이블을 먼저 삭제 해야지 부모테이블도 삭제가 가능 

--booking 을 먼저 제거 후 Food 를 제거해야함 .(외부키로 연결되어 있으므로 )

drop table booking;
drop table food;

drop table sawon;

--시퀀스도 모두 삭제
drop sequence seq_food;
drop sequence seq1;