apiVersion: v1
kind: Service
metadata:
  name: mybitser
spec:
  type: NodePort
  selector:
    app: bitcamp
  ports:
    - port: 8099
      targetPort: 8090
      protocol: TCP
      nodePort: 30060

