server:
  port: 8090

#session 유지시간 변경(기본은 30분)
  servlet:
    session:
      timeout: 90m  
#mysql setting  
spring:  
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://db-324oc2-kr.vpc-pub-cdb.ntruss.com:3306/studydb?serverTimezone=Asia/Seoul
    username: study
    password: bitcamp!@#123 

#jpa setting
#스키마 생성 create:기존테이블삭제후 생성, update:변경된 부분만 반영
  jpa:
    hibernate:
      ddl-auto: update
#ddl 생성시 데이타베이스 고유의 기능을 사용할 것인가     
    generate-ddl: true
#api 호출시 실행되는 sql 문을 콘솔에 보여줄것인가   
    show-sql: false
#사용할 데이타베이스 종류    
    database: mysql
#Mysql 상세지정   
    database-platform: org.hibernate.dialect.MySQLDialect

#swagger doc
springdoc:
  api-docs:
    path: /api/jpashop/swagger
#http://localhost:8090/swagger-ui.html


#security
jwt:
  expiration_time: 86400000 #1일
  secret: VlwEyVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkHa
